// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('./components/Content.vue')['default']
    copy: typeof import('./components/RightPanel.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIn: typeof import('element-plus/es')['ElIn']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElTag: typeof import('element-plus/es')['ElTag']
    LeftPanel: typeof import('./components/LeftPanel.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
  }
}
